# Fader/Hardie Beta-Geometric/Beta-Bernoulli CLV Model
# R. Wagner, 2021

# use conditional expectations and value multipliers to generate overall revenue forecast over N* periods
# if N* = # of testing periods, can compare forecast to actual revenue generated by these cohorts in testing period
# can use these estimates to further tune model parameters if desired

# total revenue forecast over N* months (testing period)
df_xtxn_train$ce_nstar <- compute_ce(mle_results = mle_results,
                                  n_star = holdout_periods, 
                                  df_xtxn = df_xtxn_train) 

df_ce_nstar <- subset(df_xtxn_train, select = c('x_tx_n', 'ce_nstar'))

# append conditional expectations to order matrix
df_order_matrix_train <- merge(df_order_matrix_train, df_ce_nstar, by='x_tx_n')

# EXPECTED REVENUE in testing period
# per user (CE * value multiplier)
df_order_matrix_train$rev_nstar_pred <- (df_order_matrix_train$ce_nstar * df_order_matrix_train$expected_amount)
# across all cohorts
rev_nstar_pred <- sum(df_order_matrix_train$rev_nstar_pred); rev_nstar_pred

# ACTUAL revenue in testing period
# per user
df_order_matrix_test$rev_nstar_actual <- apply(df_order_matrix_test[, paste0('t', testing_months)], 1, function(x) sum(x, na.rm=T))
# across all cohorts
rev_nstar_actual <- sum(df_order_matrix_test$rev_nstar_actual); rev_nstar_actual

# residual:
(rev_nstar_actual - rev_nstar_pred) # actual amount only ~$230K under

# forecast cumulative monthly revenue by generating different conditional expectation for N*=[1:n] (here, n=5)
# then back out 'per month' revenue forecasts as (x - lag(x))

# conditional expectations
ce <- data.frame()
df_xtxn_train$ce_n1 <- compute_ce(mle_results = mle_results, n_star = 1, df_xtxn = df_xtxn_train) 
df_xtxn_train$ce_n2 <- compute_ce(mle_results = mle_results, n_star = 2, df_xtxn = df_xtxn_train) 
df_xtxn_train$ce_n3 <- compute_ce(mle_results = mle_results, n_star = 3, df_xtxn = df_xtxn_train) 
df_xtxn_train$ce_n4 <- compute_ce(mle_results = mle_results, n_star = 4, df_xtxn = df_xtxn_train) 
df_xtxn_train$ce_n5 <- compute_ce(mle_results = mle_results, n_star = 5, df_xtxn = df_xtxn_train)

df_order_matrix_train <- merge(df_order_matrix_train, 
                               subset(df_xtxn_train, select = c('x_tx_n','ce_n1','ce_n2','ce_n3','ce_n4', 'ce_n5')),
                               by='x_tx_n')

# expected cumulative revenue
df_order_matrix_train$rev_n1_pred <- (df_order_matrix_train$ce_n1 * df_order_matrix_train$expected_amount)
df_order_matrix_train$rev_n2_pred <- (df_order_matrix_train$ce_n2 * df_order_matrix_train$expected_amount)
df_order_matrix_train$rev_n3_pred <- (df_order_matrix_train$ce_n3 * df_order_matrix_train$expected_amount)
df_order_matrix_train$rev_n4_pred <- (df_order_matrix_train$ce_n4 * df_order_matrix_train$expected_amount)
df_order_matrix_train$rev_n5_pred <- (df_order_matrix_train$ce_n5 * df_order_matrix_train$expected_amount)

rev_pred_cuml <- colSums(subset(df_order_matrix_train, select = c('rev_n1_pred',
                                                                  'rev_n2_pred', 
                                                                  'rev_n3_pred', 
                                                                  'rev_n4_pred', 
                                                                  'rev_n5_pred')))
# expected revenue per month
rev_pred <- (rev_pred_cuml - lag(rev_pred_cuml, 1, default = 0))

# actual revenue per month (then sum to get actual cuml)
rev_actual <- colSums(subset(df_order_matrix_test, select = paste0('t', testing_months)), na.rm=T)
rev_actual_cuml <- cumsum(rev_actual)

df_rev <- data.frame(testing_months, rev_pred, rev_pred_cuml, rev_actual, rev_actual_cuml)

# revenue per month
ggplot(df_rev) + 
  geom_line(aes(x=testing_months, y=rev_actual, color="Actual")) + # observed E(X)
  geom_point(aes(x=testing_months, y=rev_actual, color="Actual")) +
  geom_line(aes(x=testing_months, y=rev_pred, color="Predicted")) + # predicted E(X)
  geom_point(aes(x=testing_months, y=rev_pred, color="Predicted")) +
  scale_x_date(date_labels = "%b '%y") +
  scale_y_continuous(labels=scales::dollar_format(scale=0.000001, suffix="M")) +
  labs(title="Monthly Revenue Over Testing Months",
       subtitle = 'Among Training Cohorts',
       x="Month",
       y="Revenue",
       color="Legend") +
  theme(plot.margin = unit(c(1,1,1,1), "cm"),
        axis.text = element_text(face="bold", size=10),
        axis.title = element_text(face="bold", size=10),
        axis.title.x = element_text(vjust = -3),
        axis.title.y = element_text(vjust = 3),
        plot.title = element_text(face="bold", size=11),
        plot.subtitle = element_text(size = 9))

# cuml revenue
ggplot(df_rev) + 
  geom_line(aes(x=testing_months, y=rev_actual_cuml, color="Actual")) + # observed E(X)
  geom_point(aes(x=testing_months, y=rev_actual_cuml, color="Actual")) +
  geom_line(aes(x=testing_months, y=rev_pred_cuml, color="Predicted")) + # predicted E(X)
  geom_point(aes(x=testing_months, y=rev_pred_cuml, color="Predicted")) +
  scale_x_date(date_labels = "%b '%y") +
  scale_y_continuous(labels=scales::dollar_format(scale=0.000001, suffix="M")) +
  labs(title="Cumulative Revenue Over Testing Months",
       subtitle = 'Among Training Cohorts',
       x="Month",
       y="Revenue",
       color="Legend") +
  theme(plot.margin = unit(c(1,1,1,1), "cm"),
        axis.text = element_text(face="bold", size=10),
        axis.title = element_text(face="bold", size=10),
        axis.title.x = element_text(vjust = -3),
        axis.title.y = element_text(vjust = 3),
        plot.title = element_text(face="bold", size=11),
        plot.subtitle = element_text(size = 9))


# difference of actual vs predicted cuml revenue at end of 5 month holdout period
df_rev$rev_pred_cuml[5] - df_rev$rev_actual_cuml[5]
